name: Build Flutter APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.12'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos
    
    - name: Run tests
      run: flutter test --no-pub --coverage
      continue-on-error: true
    
    - name: Build APK
      run: flutter build apk --release --split-per-abi
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apks
        path: build/app/outputs/flutter-apk/*.apk 